# Generated by Django 5.0.4 on 2024-06-13 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='created_by_admin',
            field=models.BooleanField(default=False),
        ),
    ]
