# Generated by Django 5.0.4 on 2024-06-15 06:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        ('user', '0002_userprofile_created_by_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerProfile',
            fields=[
                ('userprofile_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.userprofile')),
                ('company_name', models.CharField(max_length=255)),
                ('contact_number', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('bank_account_number', models.CharField(max_length=100, unique=True)),
                ('bank_name', models.CharField(max_length=100)),
                ('total_sales', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('total_orders', models.PositiveIntegerField(default=0)),
                ('categories', models.ManyToManyField(related_name='sellers', to='store.category')),
            ],
            bases=('user.userprofile',),
        ),
        migrations.DeleteModel(
            name='AdminProfile',
        ),
    ]
