# Generated by Django 5.0.4 on 2024-06-25 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_customerhistory'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customerhistory',
            options={'verbose_name_plural': 'Customer History'},
        ),
    ]
