# Generated by Django 5.0.4 on 2024-06-26 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_customerhistory_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customerhistory',
            name='customer',
        ),
        migrations.AddField(
            model_name='customerhistory',
            name='username',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='customerhistory',
            name='cart',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='customerhistory',
            name='date',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='customerhistory',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
